# Generated by Django 5.1.5 on 2026-09-25 18:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('name', models.CharField(max_length=180, verbose_name='nom')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location_label', models.CharField(blank=True, max_length=200, verbose_name='localisation')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='ville')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='région')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('geofence_radius_m', models.PositiveIntegerField(default=500, verbose_name='rayon de périmètre (m)')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA (FCFA)')], default='XAF', max_length=3, verbose_name='devise')),
                ('budget_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='budget prévu (FCFA)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'En cours'), ('ON_HOLD', 'Suspendu'), ('COMPLETED', 'Terminé'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=16, verbose_name='statut')),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='avancement (%)')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='début prévu')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='fin prévue')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='début réel')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='fin réelle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Administrateur plateforme'), ('ORG_OWNER', "Promoteur / propriétaire d'organisation"), ('PROJECT_OWNER', "Maître d'ouvrage"), ('ENGINEER', "Ingénieur / bureau d'études"), ('CONTRACTOR', 'Entreprise / PME de travaux'), ('FIELD_AGENT', 'Agent terrain / chef de chantier'), ('VALIDATOR', 'Contrôleur / validateur'), ('FINANCE', 'Gestionnaire financier'), ('INVESTOR', 'Investisseur / bailleur')], max_length=32, verbose_name='rôle sur le projet')),
                ('can_validate_evidence', models.BooleanField(default=False, verbose_name='peut valider les preuves')),
                ('can_manage_finance', models.BooleanField(default=False, verbose_name='peut gérer les finances')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membre de projet',
                'verbose_name_plural': 'membres de projet',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='projects_pr_organiz_8941e0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'deleted_at'], name='projects_pr_status_e9072f_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('code', ''), _negated=True)), fields=('organization', 'code'), name='uniq_project_code_per_organization'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'is_active'], name='projects_pr_user_id_5f83f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member'),
        ),
    ]
