# Generated by Django 5.1.5 on 2026-09-25 19:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé'), ('BLOCKED', 'Bloqué'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=16, verbose_name='statut')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='date prévue')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='date réelle')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, verbose_name='poids')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_milestones', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'jalon',
                'verbose_name_plural': 'jalons',
                'ordering': ['order', 'planned_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminée'), ('BLOCKED', 'Bloquée'), ('CANCELLED', 'Annulée')], default='TODO', max_length=16, verbose_name='statut')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='début prévu')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='fin prévue')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='début réel')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='fin réelle')),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='avancement (%)')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, verbose_name='poids')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='blocking', to='projects.task', verbose_name='dépend de')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.milestone', verbose_name='jalon')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'tâche',
                'verbose_name_plural': 'tâches',
                'ordering': ['planned_start_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'status'], name='projects_mi_project_dc545b_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'deleted_at'], name='projects_mi_project_cc2269_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='projects_ta_project_cd2085_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'deleted_at'], name='projects_ta_project_a82984_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='projects_ta_assigne_df8978_idx'),
        ),
    ]
