[pytest]
DJANGO_SETTINGS_MODULE = config.settings_test
python_files = tests.py test_*.py *_tests.py
testpaths = apps
addopts = -q --strict-markers
markers =
    slow: test lent (charge, concurrence)
    security: test de sécurité
