# Generated by Django 5.2.17 on 2026-09-29 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0002_milestone_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=24)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['state', 'updated_at'], name='notificatio_state_3027dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MILESTONE_VALIDATED', 'Jalon validé'), ('EXPENSE_SUBMITTED', 'Dépense soumise'), ('EVIDENCE_REJECTED', 'Preuve rejetée'), ('BUDGET_THRESHOLD_REACHED', 'Seuil budgétaire atteint'), ('PROJECT_DELAYED', 'Projet en retard')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dispatch_error', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_events', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['dispatched_at', 'created_at'], name='notificatio_dispatc_1b8b5e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uniq_business_event_dedupe_key')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MILESTONE_VALIDATED', 'Jalon validé'), ('EXPENSE_SUBMITTED', 'Dépense soumise'), ('EVIDENCE_REJECTED', 'Preuve rejetée'), ('BUDGET_THRESHOLD_REACHED', 'Seuil budgétaire atteint'), ('PROJECT_DELAYED', 'Projet en retard')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('body', models.CharField(max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('group_key', models.CharField(max_length=180)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'last_seen_at'], name='notificatio_recipie_a08706_idx'), models.Index(fields=['recipient', 'group_key', 'read_at'], name='notificatio_recipie_5fbb08_idx')],
            },
        ),
    ]
