# Generated by Django 5.1.5 on 2026-09-25 18:23

import apps.users.roles
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email vérifié le')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='téléphone vérifié')),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Administrateur plateforme'), ('ORG_OWNER', "Promoteur / propriétaire d'organisation"), ('PROJECT_OWNER', "Maître d'ouvrage"), ('ENGINEER', "Ingénieur / bureau d'études"), ('CONTRACTOR', 'Entreprise / PME de travaux'), ('FIELD_AGENT', 'Agent terrain / chef de chantier'), ('VALIDATOR', 'Contrôleur / validateur'), ('FINANCE', 'Gestionnaire financier'), ('INVESTOR', 'Investisseur / bailleur')], default=apps.users.roles.default_role, max_length=32, verbose_name='rôle')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('password_changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='mot de passe modifié le')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='échecs de connexion')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name="verrouillé jusqu'au")),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='dernière IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], default='SMS', max_length=8, verbose_name='canal')),
                ('purpose', models.CharField(choices=[('SIGNUP', 'Activation du compte'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('EMAIL_VERIFY', "Vérification de l'email")], db_index=True, max_length=24, verbose_name='usage')),
                ('code_hash', models.CharField(max_length=128, verbose_name='empreinte du code')),
                ('salt', models.CharField(max_length=64, verbose_name='sel')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expire le')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consommé le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='agent utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code OTP',
                'verbose_name_plural': 'codes OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='uniq_user_email_active'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['phone', 'purpose', 'consumed_at'], name='users_otpco_phone_f2dd64_idx'),
        ),
    ]
