# Generated by Django 5.1.5 on 2026-09-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'Utilisateur inscrit'), ('OTP_SENT', 'OTP envoyé'), ('OTP_VERIFIED', 'OTP vérifié'), ('OTP_FAILED', 'OTP refusé'), ('OTP_RESEND', 'OTP renvoyé'), ('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Connexion échouée'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('LOGOUT', 'Déconnexion'), ('TOKEN_REFRESHED', 'Jeton rafraîchi'), ('TOKEN_REFRESH_REJECTED', 'Rafraîchissement refusé'), ('PASSWORD_RESET_REQUESTED', 'Réinitialisation demandée'), ('PASSWORD_RESET_FAILED', 'Réinitialisation échouée'), ('PASSWORD_RESET_CONFIRMED', 'Mot de passe réinitialisé'), ('PASSWORD_RESET_DENIED', 'Réinitialisation refusée'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('EMAIL_ADDED', 'Email ajouté'), ('EMAIL_VERIFIED', 'Email vérifié')], db_index=True, max_length=48, verbose_name='action')),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name="type d'entité")),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name="identifiant d'entité")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='agent utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
            ],
            options={
                'verbose_name': "journal d'activité",
                'verbose_name_plural': "journal d'activité",
                'ordering': ['-created_at'],
            },
        ),
    ]
