# Generated by Django 5.1.5 on 2026-09-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='organizations.organization', verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='projects.project', verbose_name='projet'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'Utilisateur inscrit'), ('OTP_SENT', 'OTP envoyé'), ('OTP_VERIFIED', 'OTP vérifié'), ('OTP_FAILED', 'OTP refusé'), ('OTP_RESEND', 'OTP renvoyé'), ('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Connexion échouée'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('LOGOUT', 'Déconnexion'), ('TOKEN_REFRESHED', 'Jeton rafraîchi'), ('TOKEN_REFRESH_REJECTED', 'Rafraîchissement refusé'), ('PASSWORD_RESET_REQUESTED', 'Réinitialisation demandée'), ('PASSWORD_RESET_FAILED', 'Réinitialisation échouée'), ('PASSWORD_RESET_CONFIRMED', 'Mot de passe réinitialisé'), ('PASSWORD_RESET_DENIED', 'Réinitialisation refusée'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('EMAIL_ADDED', 'Email ajouté'), ('EMAIL_VERIFIED', 'Email vérifié'), ('ORG_CREATED', 'Organisation créée'), ('ORG_UPDATED', 'Organisation modifiée'), ('PROJECT_CREATED', 'Projet créé'), ('PROJECT_UPDATED', 'Projet modifié'), ('PROJECT_ARCHIVED', 'Projet archivé'), ('MEMBER_ADDED', 'Membre ajouté'), ('MEMBER_ROLE_CHANGED', 'Rôle modifié'), ('MEMBER_REMOVED', 'Membre retiré')], db_index=True, max_length=48, verbose_name='action'),
        ),
    ]
