# Generated by Django 5.1.5 on 2026-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'Utilisateur inscrit'), ('OTP_SENT', 'OTP envoyé'), ('OTP_VERIFIED', 'OTP vérifié'), ('OTP_FAILED', 'OTP refusé'), ('OTP_RESEND', 'OTP renvoyé'), ('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Connexion échouée'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('LOGOUT', 'Déconnexion'), ('TOKEN_REFRESHED', 'Jeton rafraîchi'), ('TOKEN_REFRESH_REJECTED', 'Rafraîchissement refusé'), ('PASSWORD_RESET_REQUESTED', 'Réinitialisation demandée'), ('PASSWORD_RESET_FAILED', 'Réinitialisation échouée'), ('PASSWORD_RESET_CONFIRMED', 'Mot de passe réinitialisé'), ('PASSWORD_RESET_DENIED', 'Réinitialisation refusée'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('EMAIL_ADDED', 'Email ajouté'), ('EMAIL_VERIFIED', 'Email vérifié'), ('ORG_CREATED', 'Organisation créée'), ('ORG_UPDATED', 'Organisation modifiée'), ('PROJECT_CREATED', 'Projet créé'), ('PROJECT_UPDATED', 'Projet modifié'), ('PROJECT_ARCHIVED', 'Projet archivé'), ('MEMBER_ADDED', 'Membre ajouté'), ('MEMBER_ROLE_CHANGED', 'Rôle modifié'), ('MEMBER_REMOVED', 'Membre retiré'), ('MILESTONE_CREATED', 'Jalon créé'), ('MILESTONE_UPDATED', 'Jalon modifié'), ('MILESTONE_DELETED', 'Jalon supprimé'), ('TASK_CREATED', 'Tâche créée'), ('TASK_UPDATED', 'Tâche modifiée'), ('TASK_STATUS_CHANGED', 'Statut de tâche modifié'), ('TASK_DELETED', 'Tâche supprimée'), ('EVIDENCE_CAPTURED', 'Preuve capturée'), ('EVIDENCE_VALIDATED', 'Preuve validée'), ('EVIDENCE_REJECTED', 'Preuve rejetée'), ('EVIDENCE_FLAGGED', 'Preuve signalée'), ('EVIDENCE_REOPENED', 'Preuve rouverte'), ('BUDGET_LINE_CREATED', 'Poste budgétaire créé'), ('BUDGET_LINE_UPDATED', 'Poste budgétaire modifié'), ('BUDGET_LINE_DELETED', 'Poste budgétaire supprimé'), ('EXPENSE_CREATED', 'Dépense créée'), ('EXPENSE_UPDATED', 'Dépense modifiée'), ('EXPENSE_SUBMITTED', 'Dépense soumise'), ('EXPENSE_APPROVED', 'Dépense approuvée'), ('EXPENSE_REJECTED', 'Dépense rejetée'), ('EXPENSE_CANCELLED', 'Dépense annulée'), ('EXPENSE_RECEIPT_ATTACHED', 'Justificatif attaché'), ('PAYMENT_RECORDED', 'Paiement enregistré'), ('PAYMENT_CANCELLED', 'Paiement annulé'), ('ADJUSTMENT_RECORDED', 'Ajustement financier'), ('BUDGET_THRESHOLD_REACHED', 'Seuil budgétaire atteint'), ('BUDGET_EXCEEDED', 'Budget dépassé')], db_index=True, max_length=48, verbose_name='action'),
        ),
    ]
