# Generated by Django 5.1.5 on 2026-09-26 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('idempotency_key', models.CharField(max_length=64, verbose_name="clé d'idempotence")),
                ('operation_type', models.CharField(max_length=32, verbose_name="type d'opération")),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('DONE', 'Appliquée')], default='IN_PROGRESS', max_length=16, verbose_name='état')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="statut HTTP d'origine")),
                ('entity_type', models.CharField(blank=True, max_length=32, verbose_name="type d'entité")),
                ('entity_id', models.BigIntegerField(blank=True, null=True, verbose_name="identifiant d'entité")),
                ('response_body', models.JSONField(blank=True, default=dict, verbose_name="réponse d'origine")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'opération de synchronisation',
                'verbose_name_plural': 'opérations de synchronisation',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='sync_syncop_user_id_504456_idx'), models.Index(fields=['operation_type', 'created_at'], name='sync_syncop_operati_412530_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_sync_operation_per_user')],
            },
        ),
    ]
