# Generated by Django 5.1.5 on 2026-09-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_milestone_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('label', models.CharField(max_length=160, verbose_name='libellé')),
                ('category', models.CharField(choices=[('MATERIALS', 'Matériaux'), ('LABOUR', "Main-d'œuvre"), ('EQUIPMENT', 'Matériel et engins'), ('SUBCONTRACT', 'Sous-traitance'), ('TRANSPORT', 'Transport'), ('ADMIN', 'Frais administratifs'), ('OTHER', 'Autres')], default='MATERIALS', max_length=16, verbose_name='catégorie')),
                ('planned_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='montant prévu (FCFA)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budget_lines', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'poste budgétaire',
                'verbose_name_plural': 'postes budgétaires',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('title', models.CharField(max_length=180, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='montant (FCFA)')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='devise')),
                ('incurred_on', models.DateField(verbose_name='date de la dépense')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise à validation'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=16, verbose_name='statut')),
                ('supplier', models.CharField(blank=True, max_length=180, verbose_name='fournisseur / prestataire')),
                ('invoice_number', models.CharField(blank=True, max_length=80, verbose_name='numéro de facture')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='date de facture')),
                ('receipt', models.FileField(blank=True, max_length=255, null=True, upload_to='finance/receipts/', verbose_name='justificatif')),
                ('receipt_hash', models.CharField(blank=True, max_length=64, verbose_name='empreinte du justificatif')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approuvée le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='approuvée par')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.budgetline', verbose_name='poste budgétaire')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-incurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='montant (FCFA)')),
                ('paid_on', models.DateField(verbose_name='payé le')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque')], max_length=16, verbose_name='moyen de paiement')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='référence')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_payments', to=settings.AUTH_USER_MODEL, verbose_name='annulé par')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.expense', verbose_name='dépense')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPENSE', 'Dépense engagée'), ('PAYMENT', 'Paiement'), ('ADJUSTMENT', 'Ajustement'), ('CANCELLATION', 'Contre-écriture')], max_length=16, verbose_name='type')),
                ('direction', models.CharField(choices=[('DEBIT', 'Débit (consomme le budget)'), ('CREDIT', 'Crédit (libère le budget)')], max_length=8, verbose_name='sens')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='montant (FCFA)')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='solde après')),
                ('note', models.TextField(blank=True, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.budgetline', verbose_name='poste budgétaire')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.expense', verbose_name='dépense')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='projects.project', verbose_name='projet')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.payment', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'écriture financière',
                'verbose_name_plural': 'écritures financières',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['project', 'category'], name='finance_bud_project_8e6c64_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('project', 'label'), name='uniq_budget_line_label_per_project'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0)), name='budget_line_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'status', 'deleted_at'], name='finance_exp_project_981563_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'incurred_on'], name='finance_exp_project_954fc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__gt', '')), fields=('project', 'invoice_number'), name='uniq_expense_invoice_per_project'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['expense', 'paid_on'], name='finance_pay_expense_f0c516_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_strictly_positive'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['project', 'type', 'direction'], name='finance_fin_project_fddc96_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['project', 'created_at'], name='finance_fin_project_f5bd0f_idx'),
        ),
    ]
