# Generated by Django 5.2.17 on 2026-09-29 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0002_milestone_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_content_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='MIME réel du justificatif'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_scan_result',
            field=models.CharField(blank=True, max_length=100, verbose_name='résultat antivirus du justificatif'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_scan_status',
            field=models.CharField(choices=[('PENDING', "En attente d'analyse"), ('SCANNING', 'Analyse en cours'), ('CLEAN', 'Contrôlé sans menace'), ('INFECTED', 'Fichier bloqué'), ('ERROR', 'Analyse à relancer')], db_index=True, default='PENDING', max_length=16, verbose_name='analyse antivirus du justificatif'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='justificatif analysé le'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_size_bytes',
            field=models.PositiveIntegerField(default=0, verbose_name='taille du justificatif'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_expense_receipts', to=settings.AUTH_USER_MODEL, verbose_name='justificatif déposé par'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['receipt_scan_status', 'updated_at'], name='finance_exp_receipt_fc813b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project', 'receipt_scan_status'], name='finance_exp_project_1986f2_idx'),
        ),
    ]
