# Generated by Django 5.1.5 on 2026-09-26 08:43

import apps.evidences.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_milestone_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('file', models.FileField(max_length=255, upload_to=apps.evidences.models.evidence_upload_path, verbose_name='fichier')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='evidences/thumbnails/', verbose_name='miniature')),
                ('list_version', models.ImageField(blank=True, max_length=255, null=True, upload_to='evidences/lists/', verbose_name='version allégée')),
                ('hash_sha256', models.CharField(db_index=True, max_length=64, verbose_name='empreinte SHA-256')),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='horodatage de capture')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('gps_accuracy', models.FloatField(blank=True, null=True, verbose_name='précision GPS (m)')),
                ('gps_status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'Indisponible'), ('DENIED', "Refusée par l'utilisateur")], default='UNAVAILABLE', max_length=16, verbose_name='statut GPS')),
                ('device_model', models.CharField(blank=True, max_length=120, verbose_name='appareil')),
                ('device_platform', models.CharField(blank=True, max_length=60, verbose_name='plateforme')),
                ('app_version', models.CharField(blank=True, max_length=32, verbose_name="version de l'application")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée'), ('FLAGGED', 'Signalée')], default='PENDING', max_length=16, verbose_name='statut')),
                ('sync_status', models.CharField(choices=[('PENDING', "En attente d'envoi"), ('UPLOADING', 'Envoi en cours'), ('SYNCED', 'Reçue'), ('FAILED', "Échec d'envoi"), ('CONFLICT', 'Doublon / conflit')], default='SYNCED', max_length=16, verbose_name='synchronisation')),
                ('idempotency_key', models.CharField(max_length=64, verbose_name="clé d'idempotence")),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('content_type', models.CharField(blank=True, max_length=32, verbose_name='type MIME détecté')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='projects.project', verbose_name='projet')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='projects.task', verbose_name='tâche')),
            ],
            options={
                'verbose_name': 'preuve terrain',
                'verbose_name_plural': 'preuves terrain',
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VALIDATE', 'Validation'), ('REJECT', 'Rejet'), ('FLAG', 'Signalement'), ('REOPEN', 'Réouverture')], max_length=16, verbose_name='action')),
                ('from_status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée'), ('FLAGGED', 'Signalée')], max_length=16, verbose_name='statut avant')),
                ('to_status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée'), ('FLAGGED', 'Signalée')], max_length=16, verbose_name='statut après')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_validations', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='evidences.evidence', verbose_name='preuve')),
            ],
            options={
                'verbose_name': 'validation de preuve',
                'verbose_name_plural': 'validations de preuve',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['project', 'status', 'deleted_at'], name='evidences_e_project_eeff4f_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['author', 'created_at'], name='evidences_e_author__c1fd55_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['captured_at'], name='evidences_e_capture_56723d_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'hash_sha256'), name='uniq_evidence_hash_per_project'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('author', 'idempotency_key'), name='uniq_evidence_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='evidencevalidation',
            index=models.Index(fields=['evidence', 'created_at'], name='evidences_e_evidenc_51d5e9_idx'),
        ),
    ]
