# Generated by Django 5.1.5 on 2026-09-25 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='supprimé le')),
                ('name', models.CharField(max_length=160, verbose_name='nom')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='identifiant')),
                ('type', models.CharField(choices=[('PROMOTER', 'Promoteur immobilier'), ('PME', 'PME / entreprise de travaux'), ('ENGINEERING_FIRM', "Bureau d'études"), ('INVESTOR', 'Investisseur / bailleur'), ('PUBLIC', "Maître d'ouvrage public")], default='PROMOTER', max_length=24, verbose_name='type')),
                ('country', models.CharField(default='CM', max_length=2, verbose_name='pays')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='ville')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='adresse')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone de contact')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Administrateur plateforme'), ('ORG_OWNER', "Promoteur / propriétaire d'organisation"), ('PROJECT_OWNER', "Maître d'ouvrage"), ('ENGINEER', "Ingénieur / bureau d'études"), ('CONTRACTOR', 'Entreprise / PME de travaux'), ('FIELD_AGENT', 'Agent terrain / chef de chantier'), ('VALIDATOR', 'Contrôleur / validateur'), ('FINANCE', 'Gestionnaire financier'), ('INVESTOR', 'Investisseur / bailleur')], max_length=32, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "membre d'organisation",
                'verbose_name_plural': "membres d'organisation",
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner', 'is_active'], name='organizatio_owner_i_01d693_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_8783ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='uniq_organization_member'),
        ),
    ]
